kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python:3.7
  commands:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -e.[all]
    - ./run-tests.sh

- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
      - failure
      - success

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
      - coverage.xml
      - .coverage
  when:
    event:
      - push

- name: docker-registry
  image: plugins/docker
  network_mode: bridge
  settings:
    repo: registry.dpi.inpe.br/brazildatacube/bdc-stac
    registry: registry.dpi.inpe.br
    insecure: true
    username:
      from_secret: registry_user
    password:
      from_secret: registry_pass
    tags:
      - latest
      - ${DRONE_SEMVER}
  when:
    event:
      - tag

