language: python

cache:
    directories:
        - $HOME/.cache/pip

branches:
    only:
        - master
        - b-0.7.0
        - b-0.8.0

dist: bionic

python:
    - "3.7"

env:
    - SQLALCHEMY_DATABASE_URI="postgresql://postgres:postgres@127.0.0.1:5432/bdcdb"

services:
    - docker

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel
    - docker run --name postgres -e POSTGRES_PASSWORD=postgres -p 127.0.0.1:5432:5432 -d mdillon/postgis
    - virtualenv venv -p python3
    - source venv/bin/activate
    - git clone -b v0.2.1 --depth 1 https://github.com/brazil-data-cube/bdc-db && cd bdc-db
    - pip install .
    - bdc-db db create-db
    - bdc-db db upgrade
    - bdc-db db migrate
    - bdc-db fixtures init
    - deactivate && cd .. && rm -rf bdc-db
    - source ~/virtualenv/python3.7/bin/activate


install:
    - pip install -e .[tests,docs]

script:
    - ./run-test.sh

after_success:
    - coveralls
    
notifications:
    slack:
        rooms:
            - secure: "oRt5VsXvnretDrOhJeKteAAmq4fje+HNlIsXBQhfr5Jd2Q7ecj6+vTzWpECCg0WCN4dJLbgvyeO/zasOF/efLx7ysUj4HUbtX7L3NUr00cj0mfxsg/GyHTX0BK/UxQJptDScCH0Dr3+RXcIthypyxEIhwp/5yPYGRzTZw8jjbJ2inETuSDkbQ/OyqAetLDa++0hiNtmsOpI9lQMBAkLKWg9qigAfhdAMRn6BWNjP920olxDv6oiGYAvyjyD7XyhP2gdf5hfsfmXQ0dvhEdDvRcIiDVyCwAM73L9/9yafdBsrxSR8NeolIRDngTqvY+8wp8YUZu6RhJg2o1E8yr/9lyWKAwXlzk9VOArnvnV0uFtkuGPw+r9WySK3JOpUjCvuSF2v5B6+Sy/uEikGZNAtNdzJoKRXTFUiGHqXYrDKDUNzGG7kh3pJRiYXR/+/KBoE3t1ufBC2MJicMjlvCwqedPFTWJ0R0KRU0/x0oGNTjgCu0BXjd16ZsnCDW7YQsokpNYQvzSzJGSLLAD5acofZnplqX2RK7mqFPA3OxlMOo2l6cMSe95Ksqc27IcXCMKmIiLZrlSnlLGLBPPQcUxwBWJlfeNLhgM4v2sECeo05jJOAdZuKBjc16DI5pLPkvooWPLni8R0vETz9GY3V/jB+XdeZMER3VYVL6+37j4zgaps="
        on_sucess: always
