language: python

cache:
    directories:
        - $HOME/.cache/pip

branches:
    only:
        - master
        - b-0.7.0
        - b-0.8.0

dist: bionic

python:
    - "3.7"

env:
    - SQLALCHEMY_DATABASE_URI="postgresql://postgres:postgres@127.0.0.1:5432/bdcdb"

services:
    - docker

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel
    - docker run --name postgres -e POSTGRES_PASSWORD=postgres -p 127.0.0.1:5432:5432 -d mdillon/postgis
    - virtualenv venv -p python3
    - source venv/bin/activate
    - git clone -b v0.2.1 --depth 1 https://github.com/brazil-data-cube/bdc-db && cd bdc-db
    - pip install .
    - bdc-db db create-db
    - bdc-db db upgrade
    - bdc-db db migrate
    - bdc-db fixtures init
    - deactivate && cd .. && rm -rf bdc-db
    - source ~/virtualenv/python3.7/bin/activate


install:
    - pip install -e .[tests,docs]

script:

    - ./run-test.sh

after_success:
    - coveralls
